### ISSUE TITLE
Some quick comments about kubeflow API

### ISSUE THREAD

**Issue by ScorpioCPH** [caicloud/kubeflow-clientset#18]
Hi, I take a look at this API repo, here are some quick comments:

- Which scope of TFJob CRD is, cluster or namespace?
  - The current example is `Namespaced` scope.
  - Cluster scope may be better.
- We have an `ObjectMeta.UID` which is unique, should we need `TFJobSpec.RuntimeID`?
- Does `PodTemplateSpec` satisfy our requirements, should we add some additional infos which are ML(TensorFlow) specified?
- YAMLs in example not work now with some external dependencies.
  - some glusterfs infos.
  - I will send a PR about this.

@DjangoPeng @ddysher @gaocegege-caicloud @lienhua34  PTAL.

**Comment by DjangoPeng** [comment]
Hi @ScorpioCPH , thanks for your comments!~

Actually, I'm not familiar with the K8s conventions, so I have some questions in the following:

> Cluster scope may be better.

Is it a convention?

> We have an ObjectMeta.UID which is unique, should we need TFJobSpec.RuntimeID?

We keep the same field as upstream, and I know it's an unique ID for resource in K8s cluster. What's the design purpose of `ObjectMeta.UID`?

> Does PodTemplateSpec satisfy our requirements, should we add some additional infos which are ML(TensorFlow) specified?

For now, we don't face the bottleneck. Maybe when we implement the logic of distributed TensorFlow training jobs, we can assess and review the PR. Do you have any suggestions on the CRD?

> YAMLs in example not work now with some external dependencies.

Thanks for your PR, and we can discuss it in the corresponding [PR](https://github.com/caicloud/kubeflow-clientset/pull/19)

**Comment by ScorpioCPH** [comment]
- If TFJob CRD is defined as `namespace` scope, it only take effect in this namespace.
  - if not explicitly defined, kubernetes will use `default` namespace by default, that means all TFJobs will fall on this `default` namespace.
  - you can't deploy TFJobs on other user-defined namespaces.
- `ObjectMeta.UID` is unique and it is populated by the system automatically, it is `Read-only`, if we just want an unique ID, we can reuse this. More info is [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md).
- Revisiting this CRD Spec definition later sounds good to me.

**Comment by ScorpioCPH** [comment]
- After revisiting, namespace scope is ok:
  - it means all TFJobs objects will have a namespace value, if not specified, will use `default`. 

Closed.
