### ISSUE TITLE
setup travis and coverall?

### ISSUE THREAD

**Issue by Jimexist** [caicloud/kubeflow-clientset#4]
this is a public repo so I think we can leverage many open source friendly tools

**Comment by gaocegege-caicloud** [comment]
SGTM, I will file a PR for the issue.

**Comment by gaocegege** [comment]
@Jimexist Would you mind enabling the repo in https://travis-ci.org/caicloud/kubeflow-clientset?

I and @gaocegege-caicloud would appreciate.

**Comment by Jimexist** [comment]
travis is done

**Comment by Jimexist** [comment]
add https://coveralls.io/ please

**Comment by gaocegege-caicloud** [comment]
There is no test now and all the code is generated, do we need to import code coverage test?

**Comment by Jimexist** [comment]
in that case let me close this.
