### ISSUE TITLE
[Discussion] Field name `tfReplica` in CRD

### ISSUE THREAD

**Issue by gaocegege-caicloud** [caicloud/kubeflow-clientset#5]
I am not sure why Jeremy uses `replica` in the CRD, but I think `replica` is a concept in kubernetes. I am not sure if we should use it in the CRD def.

Maybe we could file a issue to discuss the problem to upstream.

**Comment by gaocegege-caicloud** [comment]
Besides this, the controller won't use replica set or replica controller to run training jobs, then it is not appropriate to use replica, IMO.

**Comment by lienhua34** [comment]
`replica` also is a concept in distributed TensorFlow.

**Comment by gaocegege-caicloud** [comment]
Got it.
